export const hiragana = [
  [
    { kanji: "あ", romanji: "a" },
    { kanji: "い", romanji: "i" },
    { kanji: "う", romanji: "u" },
    { kanji: "え", romanji: "e" },
    { kanji: "お", romanji: "o" },
  ],
  [
    { kanji: "か", romanji: "ka" },
    { kanji: "き", romanji: "ki" },
    { kanji: "く", romanji: "ku" },
    { kanji: "け", romanji: "ke" },
    { kanji: "こ", romanji: "ko" },
  ],
  [
    { kanji: "さ", romanji: "sa" },
    { kanji: "し", romanji: "shi" },
    { kanji: "す", romanji: "su" },
    { kanji: "せ", romanji: "se" },
    { kanji: "そ", romanji: "so" },
  ],
  [
    { kanji: "た", romanji: "ta" },
    { kanji: "ち", romanji: "chi" },
    { kanji: "つ", romanji: "tsu" },
    { kanji: "て", romanji: "te" },
    { kanji: "と", romanji: "to" },
  ],
  [
    { kanji: "な", romanji: "na" },
    { kanji: "に", romanji: "ni" },
    { kanji: "ぬ", romanji: "nu" },
    { kanji: "ね", romanji: "ne" },
    { kanji: "の", romanji: "no" },
  ],
  [
    { kanji: "は", romanji: "ha" },
    { kanji: "ひ", romanji: "hi" },
    { kanji: "ふ", romanji: "fu" },
    { kanji: "へ", romanji: "he" },
    { kanji: "ほ", romanji: "ho" },
  ],
  [
    { kanji: "ま", romanji: "ma" },
    { kanji: "み", romanji: "mi" },
    { kanji: "む", romanji: "mu" },
    { kanji: "め", romanji: "me" },
    { kanji: "も", romanji: "mo" },
  ],
  [
    { kanji: "や", romanji: "ya" },
    { kanji: "ゆ", romanji: "yu" },
    { kanji: "よ", romanji: "yo" },
  ],
  [
    { kanji: "ら", romanji: "ra" },
    { kanji: "り", romanji: "ri" },
    { kanji: "る", romanji: "ru" },
    { kanji: "れ", romanji: "re" },
    { kanji: "ろ", romanji: "ro" },
  ],
  [
    { kanji: "わ", romanji: "wa" },
    { kanji: "を", romanji: "wo" },
  ],
  [{ kanji: "ん", romanji: "n" }],
  [
    { kanji: "が", romanji: "ga" },
    { kanji: "ぎ", romanji: "gi" },
    { kanji: "ぐ", romanji: "gu" },
    { kanji: "げ", romanji: "ge" },
    { kanji: "ご", romanji: "go" },
  ],
  [
    { kanji: "ざ", romanji: "za" },
    { kanji: "じ", romanji: "ji" },
    { kanji: "ず", romanji: "zu" },
    { kanji: "ぜ", romanji: "ze" },
    { kanji: "ぞ", romanji: "zo" },
  ],
  [
    { kanji: "だ", romanji: "da" },
    { kanji: "ぢ", romanji: "di" },
    { kanji: "づ", romanji: "du" },
    { kanji: "で", romanji: "de" },
    { kanji: "ど", romanji: "do" },
  ],
  [
    { kanji: "ば", romanji: "ba" },
    { kanji: "び", romanji: "bi" },
    { kanji: "ぶ", romanji: "bu" },
    { kanji: "べ", romanji: "be" },
    { kanji: "ぼ", romanji: "bo" },
  ],
  [
    { kanji: "ぱ", romanji: "pa" },
    { kanji: "ぴ", romanji: "pi" },
    { kanji: "ぷ", romanji: "pu" },
    { kanji: "ぺ", romanji: "pe" },
    { kanji: "ぽ", romanji: "po" },
  ],
];

export const katakana = [
  [
    { kanji: "ア", romanji: "a" },
    { kanji: "イ", romanji: "i" },
    { kanji: "ウ", romanji: "u" },
    { kanji: "エ", romanji: "e" },
    { kanji: "オ", romanji: "o" },
  ],
  [
    { kanji: "カ", romanji: "ka" },
    { kanji: "キ", romanji: "ki" },
    { kanji: "ク", romanji: "ku" },
    { kanji: "ケ", romanji: "ke" },
    { kanji: "コ", romanji: "ko" },
  ],
  [
    { kanji: "サ", romanji: "sa" },
    { kanji: "シ", romanji: "shi" },
    { kanji: "ス", romanji: "su" },
    { kanji: "セ", romanji: "se" },
    { kanji: "ソ", romanji: "so" },
  ],
  [
    { kanji: "タ", romanji: "ta" },
    { kanji: "チ", romanji: "chi" },
    { kanji: "ツ", romanji: "tsu" },
    { kanji: "テ", romanji: "te" },
    { kanji: "ト", romanji: "to" },
  ],
  [
    { kanji: "ナ", romanji: "na" },
    { kanji: "ニ", romanji: "ni" },
    { kanji: "ヌ", romanji: "nu" },
    { kanji: "ネ", romanji: "ne" },
    { kanji: "ノ", romanji: "no" },
  ],
  [
    { kanji: "ハ", romanji: "ha" },
    { kanji: "ヒ", romanji: "hi" },
    { kanji: "フ", romanji: "fu" },
    { kanji: "ヘ", romanji: "he" },
    { kanji: "ホ", romanji: "ho" },
  ],
  [
    { kanji: "マ", romanji: "ma" },
    { kanji: "ミ", romanji: "mi" },
    { kanji: "ム", romanji: "mu" },
    { kanji: "メ", romanji: "me" },
    { kanji: "モ", romanji: "mo" },
  ],
  [
    { kanji: "ヤ", romanji: "ya" },
    { kanji: "ユ", romanji: "yu" },
    { kanji: "ヨ", romanji: "yo" },
  ],
  [
    { kanji: "ラ", romanji: "ra" },
    { kanji: "リ", romanji: "ri" },
    { kanji: "ル", romanji: "ru" },
    { kanji: "レ", romanji: "re" },
    { kanji: "ロ", romanji: "ro" },
  ],
  [
    { kanji: "ワ", romanji: "wa" },
    { kanji: "ヲ", romanji: "wo" },
  ],
  [{ kanji: "ン", romanji: "n" }],
  [
    { kanji: "ガ", romanji: "ga" },
    { kanji: "ギ", romanji: "gi" },
    { kanji: "グ", romanji: "gu" },
    { kanji: "ゲ", romanji: "ge" },
    { kanji: "ゴ", romanji: "go" },
  ],
  [
    { kanji: "ザ", romanji: "za" },
    { kanji: "ジ", romanji: "ji" },
    { kanji: "ズ", romanji: "zu" },
    { kanji: "ゼ", romanji: "ze" },
    { kanji: "ゾ", romanji: "zo" },
  ],
  [
    { kanji: "ダ", romanji: "da" },
    { kanji: "ヂ", romanji: "ji" },
    { kanji: "ヅ", romanji: "zu" },
    { kanji: "デ", romanji: "de" },
    { kanji: "ド", romanji: "do" },
  ],
  [
    { kanji: "バ", romanji: "ba" },
    { kanji: "ビ", romanji: "bi" },
    { kanji: "ブ", romanji: "bu" },
    { kanji: "ベ", romanji: "be" },
    { kanji: "ボ", romanji: "bo" },
  ],
  [
    { kanji: "パ", romanji: "pa" },
    { kanji: "ピ", romanji: "pi" },
    { kanji: "プ", romanji: "pu" },
    { kanji: "ペ", romanji: "pe" },
    { kanji: "ポ", romanji: "po" },
  ],
];
